<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise的catch方法</title>
</head>
<body>
<script>
    const p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            // 设置p对象的状态为失败，并且设置失败的值
            reject('出错啦~');
        },1000);
    });

    // p.then(function (value) {

    // },function (reason) {
    //     console.error(reason);
    // });

    // catch方法直接指定失败的回调函数
    p.catch(function (reason) {
        console.warn(reason);
    });

</script>
</body>
</html>